<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">REDCapTextCleaner</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCWluc3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJpbnN0cmluZyIgKTsNCglib29sZWFuIGNvbnZlcnRUb1VwcGVyID0gQm9vbGVhbi5w
YXJzZUJvb2xlYW4oSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJjb252ZXJ0
VG9VcHBlciIpKTsNCgkvL1N0cmluZwljb252ZXJ0VG9VcHBlciA9IElEYXRhVXRpbC5nZXRTdHJp
bmcoIHBpcGVsaW5lQ3Vyc29yLCAiY29udmVydFRvVXBwZXIiICk7DQoJLy8gY3JlYXRlIHJlZ2V4
IHN0cmluZyB0byBjYXRjaCB0cmFpbGluZyBzcGFjZXMNCgkvLy5yZXBsYWNlQWxsKCJbXlxcd1xc
eEFFXFx4QTl+LiAtXSIsICJfVE1fIikNCglTdHJpbmcgcmVnZXggPSAiXFxzKyQiOw0KCQ0KCWlm
IChpbnN0cmluZyE9bnVsbCkgew0KCQlpbnN0cmluZyA9IGluc3RyaW5nLnJlcGxhY2VBbGwoIiUi
LCAiX1BSXyIpLnJlcGxhY2VBbGwoIlx1MjEyMiIsICJfVE1fIikucmVwbGFjZUFsbChyZWdleCwg
IiIpLnJlcGxhY2UoJyAnLCAnXycpLnJlcGxhY2UoJzsnLCAnXycpLnJlcGxhY2UoJy8nLCAnXycp
LnJlcGxhY2UoJ1snLCdfJykucmVwbGFjZSgnXScsICdfJykucmVwbGFjZSgnXicsICdfJykucmVw
bGFjZSgneycsICdfJykucmVwbGFjZSgnfScsICdfJykucmVwbGFjZSgnKycsICdfJykucmVwbGFj
ZSgnIycsJ18nKS5yZXBsYWNlKCcoJywgJ18nKS5yZXBsYWNlKCcuJywgJ18nKS5yZXBsYWNlKCct
JywgJ18nKS5yZXBsYWNlKCc6JywgJ18nKS5yZXBsYWNlKCcsJywgJ18nKS5yZXBsYWNlKCcmJywg
J18nKS5yZXBsYWNlKCcpJywgJ18nKS5yZXBsYWNlQWxsKCI9IiwgIkVRIikucmVwbGFjZUFsbCgi
PiIsICJHVCIpLnJlcGxhY2VBbGwoIjwiLCAiTFQiKS5yZXBsYWNlQWxsKCJtb2wtIiwgIl9taW51
cyIpLnJlcGxhY2VBbGwoIm1vbCsiLCAiX3BsdXMiKTsNCgkNCgkJaWYgKGNvbnZlcnRUb1VwcGVy
KXsNCgkJCWluc3RyaW5nID0gaW5zdHJpbmcudG9VcHBlckNhc2UoKTsNCgkJfQ0KCQ0KCX0gCWVs
c2UgaWYgKGluc3RyaW5nPT1udWxsKSB7DQoJCWluc3RyaW5nID0gIiAiOw0KCX0NCi8vIHBpcGVs
aW5lDQoNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAib3V0c3RyaW5nIiwgaW5zdHJp
bmcgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCgk=</value>
</Values>
