<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">REDCapTextCleaner</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCWluc3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJpbnN0cmluZyIgKTsNCglib29sZWFuIGNvbnZlcnRUb1VwcGVyID0gQm9vbGVhbi5w
YXJzZUJvb2xlYW4oSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJjb252ZXJ0
VG9VcHBlciIpKTsNCgkvL1N0cmluZwljb252ZXJ0VG9VcHBlciA9IElEYXRhVXRpbC5nZXRTdHJp
bmcoIHBpcGVsaW5lQ3Vyc29yLCAiY29udmVydFRvVXBwZXIiICk7DQoJLy8gY3JlYXRlIHJlZ2V4
IHN0cmluZyB0byBjYXRjaCB0cmFpbGluZyBzcGFjZXMNCglTdHJpbmcgcmVnZXggPSAiXFxzKyQi
Ow0KCQ0KCWlmIChpbnN0cmluZyE9bnVsbCkgew0KCQlpbnN0cmluZyA9IGluc3RyaW5nLnJlcGxh
Y2VBbGwoIlx1MjEyMiIsICJfVE1fIikucmVwbGFjZUFsbCgiW15cXHdcXHhBRVxceEE5fi4gLV0i
LCAiX1RNXyIpLnJlcGxhY2VBbGwocmVnZXgsICIiKS5yZXBsYWNlKCcgJywgJ18nKS5yZXBsYWNl
KCc7JywgJ18nKS5yZXBsYWNlKCcvJywgJ18nKS5yZXBsYWNlKCdbJywnXycpLnJlcGxhY2UoJ10n
LCAnXycpLnJlcGxhY2UoJ14nLCAnXycpLnJlcGxhY2UoJ3snLCAnXycpLnJlcGxhY2UoJ30nLCAn
XycpLnJlcGxhY2UoJysnLCAnXycpLnJlcGxhY2UoJyMnLCdfJykucmVwbGFjZSgnKCcsICcgJyku
cmVwbGFjZSgnLicsICdfJykucmVwbGFjZSgnLScsICdfJykucmVwbGFjZSgnOicsICAnXycpLnJl
cGxhY2UoJywnLCAnXycpLnJlcGxhY2UoJyYnLCAnXycpLnJlcGxhY2UoJyknLCAnXycpLnJlcGxh
Y2VBbGwoIj0iLCAiRVEiKS5yZXBsYWNlQWxsKCI+IiwgIkdUIikucmVwbGFjZUFsbCgiPCIsICJM
VCIpLnJlcGxhY2VBbGwoIm1vbC0iLCAiX21pbnVzIikucmVwbGFjZUFsbCgibW9sKyIsICJfcGx1
cyIpLnJlcGxhY2VBbGwoIiUiLCAicGVyY2VudCIpOw0KCQ0KCQlpZiAoY29udmVydFRvVXBwZXIp
ew0KCQkJaW5zdHJpbmcgPSBpbnN0cmluZy50b1VwcGVyQ2FzZSgpOw0KCQl9DQoJDQoJfSAJZWxz
ZSBpZiAoaW5zdHJpbmc9PW51bGwpIHsNCgkJaW5zdHJpbmcgPSAiICI7DQoJfQ0KLy8gcGlwZWxp
bmUNCg0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJvdXRzdHJpbmciLCBpbnN0cmlu
ZyApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KCQ==</value>
</Values>
