<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replaceSpecialCharacters</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCgkJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCgkJU3RyaW5nCWluU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxp
bmVDdXJzb3IsICJpblN0cmluZyIgKTsNCgkJDQoJCWlmIChpblN0cmluZyE9bnVsbCl7DQoJCQkv
L2luU3RyaW5nID0gaW5TdHJpbmcucmVwbGFjZUFsbCgiXHUyMTIyIiwgIlRNIik7DQoJCQlpblN0
cmluZyA9IGluU3RyaW5nLnJlcGxhY2VBbGwoIlx1MjEyMiIsICJUTSIpLnJlcGxhY2VBbGwoIlte
XFx3XFx4QUVcXHhBOX4uIC1dIiwgIlRNIik7DQoJCQkvL2luU3RyaW5nID0gaW5TdHJpbmcucmVw
bGFjZUFsbCgiICAiLCAiICIpOw0KCQl9IGVsc2UgaWYgKGluU3RyaW5nPT1udWxsKSB7DQoJCQlp
blN0cmluZyA9ICIgIjsNCgkJfQ0KCQkvLyBwaXBlbGluZSBvdXRwdXQNCgkJSURhdGFVdGlsLnB1
dCggcGlwZWxpbmVDdXJzb3IsICJvdXRTdHJpbmciLCBpblN0cmluZyApOw0KCQlwaXBlbGluZUN1
cnNvci5kZXN0cm95KCk7DQoNCgk=</value>
</Values>
