<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">HTMLDecodeplusEncodingXML</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5ew0KCQ0KCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29y
KCk7DQoJU3RyaW5nIGluU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJpblN0cmluZyIgKTsNCglTdHJpbmcgdmFsdWUgPSBudWxsOw0KCWlmKCBpblN0cmluZyAh
PSBudWxsICl7DQoJCUlEYXRhIG91dHB1dCA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsNCgkJb3V0
cHV0ID0gU2VydmljZS5kb0ludm9rZSgicHViLnN0cmluZyIsIkhUTUxEZWNvZGUiLCBwaXBlbGlu
ZSk7DQoNCgkvLyBwaXBlbGluZQ0KCQlJRGF0YUN1cnNvciBvdXRwdXRDdXJzb3IgPSBvdXRwdXQu
Z2V0Q3Vyc29yKCk7IA0KCQl2YWx1ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIG91dHB1dEN1cnNv
ciwgInZhbHVlIiApOw0KCQlvdXRwdXRDdXJzb3IuZGVzdHJveSgpOw0KCQl2YWx1ZSA9IHZhbHVl
LnJlcGxhY2UoIjwiLCAiJmx0OyIpLnJlcGxhY2UoIj4iLCImZ3Q7IikucmVwbGFjZSgiXCIiLCIm
cXVvdDsiKS5yZXBsYWNlKCInIiwiJiMzOSIpOw0KCX0NCgkvLyBwaXBlbGluZQ0KCWlmKCB2YWx1
ZSAhPSBudWxsICkNCgkJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJ2YWx1ZSIsIHZh
bHVlICk7DQoJcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQp9IGNhdGNoKCBFeGNlcHRpb24g
ZSl7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS50b1N0cmluZygpICk7DQp9</value>
</Values>
