<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeFiles</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJZmlsZVBhdGggPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgImZpbGVQYXRoIiApOw0KU3RyaW5nIHppcEZpbGVOYW1lID0gSURhdGFVdGlsLmdldFN0
cmluZyggcGlwZWxpbmVDdXJzb3IsICJ6aXBGaWxlTmFtZSIpOw0KRmlsZSBmaWxlID0gbmV3IEZp
bGUoZmlsZVBhdGgpOw0KRmlsZSB6aXBGaWxlID0gbmV3IEZpbGUoemlwRmlsZU5hbWUpOw0KcGlw
ZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQppZiggZmlsZVBhdGggIT0gbnVsbCApDQoJZm9yIChG
aWxlIHN1YkZpbGUgOiBmaWxlLmxpc3RGaWxlcygpKSB7DQogICAgICAgICAgICBzdWJGaWxlLmRl
bGV0ZSgpOw0KICAgICAgICAgfQ0KDQppZiggemlwRmlsZU5hbWUgIT0gbnVsbCkNCgl6aXBGaWxl
LmRlbGV0ZSgpOw0KICAgICAgDQoNCgk=</value>
</Values>
