<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">setPropertyValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
Zwlwa2duYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJwYWNrYWdl
TmFtZSIgKTsNClN0cmluZyAgcHJvcGVydHlGaWxlTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmco
cGlwZWxpbmVDdXJzb3IsInByb3BlcnR5RmlsZU5hbWUiKTsNClN0cmluZwlwcm9wZXJ0eSA9IElE
YXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAicHJvcGVydHkiICk7DQpTdHJpbmcg
IHByb3BlcnR5VmFsdWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29yLCAicHJv
cGVydHlWYWx1ZSIgKTsNCnRyeXsNCglJbnB1dFN0cmVhbSBpcyA9IG5ldyBGaWxlSW5wdXRTdHJl
YW0oU2VydmVyQVBJLmdldFBhY2thZ2VDb25maWdEaXIocGtnbmFtZSkudG9TdHJpbmcoKSsiLyIr
cHJvcGVydHlGaWxlTmFtZSk7DQoJUHJvcGVydGllcyBwcm9wID0gbmV3IFByb3BlcnRpZXMoKTsN
Cglwcm9wLmxvYWQoaXMpOw0KCWlzLmNsb3NlKCk7DQoJT3V0cHV0U3RyZWFtIG9zID0gbmV3IEZp
bGVPdXRwdXRTdHJlYW0oU2VydmVyQVBJLmdldFBhY2thZ2VDb25maWdEaXIocGtnbmFtZSkudG9T
dHJpbmcoKSsiLyIrcHJvcGVydHlGaWxlTmFtZSk7DQoJcHJvcC5zZXRQcm9wZXJ0eShwcm9wZXJ0
eSwgcHJvcGVydHlWYWx1ZSk7DQoJcHJvcC5zdG9yZShvcywgIiIpOw0KCW9zLmNsb3NlKCk7DQp9
IGNhdGNoIChFeGNlcHRpb24gZSl7DQoJLy9JRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwg
Im1zZyIsIGUudG9TdHJpbmcoKSApOw0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUudG9T
dHJpbmcoKSk7DQp9DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
