<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getPropertyValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
Zwlwa2duYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJwYWNrYWdl
TmFtZSIgKTsNClN0cmluZyAgcHJvcGVydHlGaWxlTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmco
cGlwZWxpbmVDdXJzb3IsInByb3BlcnR5RmlsZU5hbWUiKTsNClN0cmluZwlwcm9wZXJ0eSA9IElE
YXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAicHJvcGVydHkiICk7DQp0cnl7DQoJ
SW5wdXRTdHJlYW0gaXMgPSBuZXcgRmlsZUlucHV0U3RyZWFtKFNlcnZlckFQSS5nZXRQYWNrYWdl
Q29uZmlnRGlyKHBrZ25hbWUpLnRvU3RyaW5nKCkrIi8iK3Byb3BlcnR5RmlsZU5hbWUpOw0KCVBy
b3BlcnRpZXMgcHJvcCA9IG5ldyBQcm9wZXJ0aWVzKCk7DQoJcHJvcC5sb2FkKGlzKTsNCglJRGF0
YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwgInByb3BlcnR5VmFsdWUiLCBwcm9wLmdldFByb3Bl
cnR5KHByb3BlcnR5LCAiIikgKTsNCglpcy5jbG9zZSgpOw0KfSBjYXRjaCAoRXhjZXB0aW9uIGUp
ew0KCS8vSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJtc2ciLCBlLnRvU3RyaW5nKCkg
KTsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLnRvU3RyaW5nKCkpOw0KfQ0KcGlwZWxp
bmVDdXJzb3IuZGVzdHJveSgpOw0KCQ==</value>
</Values>
