<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ps</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpWZWN0b3I8U3RyaW5nPiB2ZWN0b3IgPSBuZXcgVmVjdG9yPFN0cmluZz4oKTsNCgkJ
IA0KdHJ5IHsNCiAgICBQcm9jZXNzIHByb2Nlc3MgPSBSdW50aW1lLmdldFJ1bnRpbWUoKS5leGVj
KG5ldyBTdHJpbmdbXXsiL2Jpbi9zaCIsIi1jIiwgInBzIC1mdSBzYWd1c2VyIHwgZ3JlcCAtdiBc
InBzIC1mdSBzYWd1c2VyXCIifSk7DQogDQogICAgQnVmZmVyZWRSZWFkZXIgcmVhZGVyID0gbmV3
IEJ1ZmZlcmVkUmVhZGVyKG5ldyBJbnB1dFN0cmVhbVJlYWRlcihwcm9jZXNzLmdldElucHV0U3Ry
ZWFtKCkpKTsNCiAgICBTdHJpbmcgbGluZTsNCiAgICB3aGlsZSAoKGxpbmUgPSByZWFkZXIucmVh
ZExpbmUoKSkgIT0gbnVsbCkgew0KICAgICAgICB2ZWN0b3IuYWRkKGxpbmUpOw0KICAgIH0NCiAN
CiAgICByZWFkZXIuY2xvc2UoKTsNCiANCn0gY2F0Y2ggKElPRXhjZXB0aW9uIGUpIHsNCiAgICB2
ZWN0b3IuYWRkKCBlLnRvU3RyaW5nKCkgKTsNCn0NCg0KLy9JRGF0YUN1cnNvciBwaXBlbGluZUN1
cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJz
b3IsICJvdXRwdXQiLCB2ZWN0b3IudG9BcnJheShuZXcgU3RyaW5nW3ZlY3Rvci5zaXplKCldKSAp
Ow0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
