<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">free</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpWZWN0b3I8U3RyaW5nPiB2ZWN0b3IgPSBuZXcgVmVjdG9yPFN0cmluZz4oKTsNCgkJ
IA0KdHJ5IHsNCiAgICBQcm9jZXNzIHByb2Nlc3MgPSBSdW50aW1lLmdldFJ1bnRpbWUoKS5leGVj
KG5ldyBTdHJpbmdbXXsiL2Jpbi9zaCIsIi1jIiwgImZyZWUgLWgifSk7DQogDQogICAgQnVmZmVy
ZWRSZWFkZXIgcmVhZGVyID0gbmV3IEJ1ZmZlcmVkUmVhZGVyKG5ldyBJbnB1dFN0cmVhbVJlYWRl
cihwcm9jZXNzLmdldElucHV0U3RyZWFtKCkpKTsNCiAgICBTdHJpbmcgbGluZTsNCiAgICB3aGls
ZSAoKGxpbmUgPSByZWFkZXIucmVhZExpbmUoKSkgIT0gbnVsbCkgew0KICAgICAgICB2ZWN0b3Iu
YWRkKGxpbmUpOw0KICAgIH0NCiANCiAgICByZWFkZXIuY2xvc2UoKTsNCiANCn0gY2F0Y2ggKElP
RXhjZXB0aW9uIGUpIHsNCiAgICB2ZWN0b3IuYWRkKCBlLnRvU3RyaW5nKCkgKTsNCn0NCg0KLy9J
RGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFV
dGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJvdXRwdXQiLCB2ZWN0b3IudG9BcnJheShuZXcgU3Ry
aW5nW3ZlY3Rvci5zaXplKCldKSApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
