<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replacementRule</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW5wdXQNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUu
Z2V0Q3Vyc29yKCk7DQpTdHJpbmcJc3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxp
bmVDdXJzb3IsICJzdHJpbmciICk7DQpib29sZWFuIGNvbnZlcnRUb1VwcGVyID0gQm9vbGVhbi5w
YXJzZUJvb2xlYW4oSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJjb252ZXJ0
VG9VcHBlciIpKTsNCmlmIChzdHJpbmchPW51bGwpew0KCXN0cmluZyA9IHN0cmluZy5yZXBsYWNl
KCcgJywgJ18nKS5yZXBsYWNlKCc7JywgJ18nKS5yZXBsYWNlKCcvJywgJ18nKS5yZXBsYWNlKCco
JywgJ18nKS5yZXBsYWNlKCcuJywgJ18nKS5yZXBsYWNlKCctJywgJ18nKS5yZXBsYWNlKCc6Jywg
ICdfJykucmVwbGFjZSgnLCcsICdfJykucmVwbGFjZSgnJicsICdfJykucmVwbGFjZSgnKScsICdf
JykucmVwbGFjZUFsbCgiXHUyMTIyIiwgIiIpOw0KCWlmKCBjb252ZXJ0VG9VcHBlciApew0KCQlz
dHJpbmcgPSBzdHJpbmcudG9VcHBlckNhc2UoKTsNCgl9DQp9IGVsc2UgaWYgKHN0cmluZz09bnVs
bCkgew0KCXN0cmluZyA9ICIgIjsNCn0NCi8vIHBpcGVsaW5lIG91dHB1dA0KSURhdGFVdGlsLnB1
dCggcGlwZWxpbmVDdXJzb3IsICJ0cmFuc2Zvcm1lZFN0cmluZyIsIHN0cmluZyApOw0KcGlwZWxp
bmVDdXJzb3IuZGVzdHJveSgpOw0KCQ==</value>
</Values>
