<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replacementRule</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW5wdXQNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUu
Z2V0Q3Vyc29yKCk7DQpTdHJpbmcJc3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxp
bmVDdXJzb3IsICJzdHJpbmciICk7DQpib29sZWFuIGNvbnZlcnRUb1VwcGVyID0gQm9vbGVhbi5w
YXJzZUJvb2xlYW4oSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJjb252ZXJ0
VG9VcHBlciIpKTsNCmlmIChzdHJpbmchPW51bGwpew0KCXN0cmluZyA9IHN0cmluZy5yZXBsYWNl
KCcgJywgJ18nKS5yZXBsYWNlKCc7JywgJ18nKS5yZXBsYWNlKCcvJywgJ18nKS5yZXBsYWNlKCco
JywgJ18nKS5yZXBsYWNlKCcuJywgJ18nKS5yZXBsYWNlKCctJywgJ18nKS5yZXBsYWNlKCc6Jywg
ICdfJykucmVwbGFjZSgnLCcsICdfJykucmVwbGFjZSgnJicsICdfJykucmVwbGFjZSgnKScsICdf
JykucmVwbGFjZUFsbCgiXHUyMTIyIiwgIl9UTSIpLnJlcGxhY2VBbGwoIlteXFx3XFx4QUVcXHhB
OX4uIC1dIiwgIl9UTSIpOw0KCWlmKCBjb252ZXJ0VG9VcHBlciApew0KCQlzdHJpbmcgPSBzdHJp
bmcudG9VcHBlckNhc2UoKTsNCgl9DQp9IGVsc2UgaWYgKHN0cmluZz09bnVsbCkgew0KCXN0cmlu
ZyA9ICIgIjsNCn0NCi8vIHBpcGVsaW5lIG91dHB1dA0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVD
dXJzb3IsICJ0cmFuc2Zvcm1lZFN0cmluZyIsIHN0cmluZyApOw0KcGlwZWxpbmVDdXJzb3IuZGVz
dHJveSgpOw0KCQ0KCQ==</value>
</Values>
