<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replacementRule</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW5wdXQNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUu
Z2V0Q3Vyc29yKCk7DQpTdHJpbmcJc3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxp
bmVDdXJzb3IsICJzdHJpbmciICk7DQpib29sZWFuIGNvbnZlcnRUb1VwcGVyID0gQm9vbGVhbi5w
YXJzZUJvb2xlYW4oSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJjb252ZXJ0
VG9VcHBlciIpKTsNCmlmIChzdHJpbmchPW51bGwpew0KCXN0cmluZyA9IHN0cmluZy5yZXBsYWNl
KCcgJywgJ18nKS5yZXBsYWNlKCc7JywgJ18nKS5yZXBsYWNlKCcvJywgJ18nKS5yZXBsYWNlKCco
JywgJ18nKS5yZXBsYWNlKCcuJywgJ18nKS5yZXBsYWNlKCctJywgJ18nKS5yZXBsYWNlKCc6Jywg
ICdfJykucmVwbGFjZSgnLCcsICdfJykucmVwbGFjZSgnJicsICdfJykucmVwbGFjZSgnKScsICdf
JykucmVwbGFjZUFsbCgiXHUyMTIyIiwgIl8iKS5yZXBsYWNlQWxsKCJbXlxcd1xceEFFXFx4QTl+
LiAtXSIsICJfIik7DQoJaWYoIGNvbnZlcnRUb1VwcGVyICl7DQoJCXN0cmluZyA9IHN0cmluZy50
b1VwcGVyQ2FzZSgpOw0KCX0NCn0gZWxzZSBpZiAoc3RyaW5nPT1udWxsKSB7DQoJc3RyaW5nID0g
IiAiOw0KfQ0KLy8gcGlwZWxpbmUgb3V0cHV0DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNv
ciwgInRyYW5zZm9ybWVkU3RyaW5nIiwgc3RyaW5nICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95
KCk7DQoJ</value>
</Values>
