<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">itemCount</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCWluU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJpblN0cmluZyIgKTsNCglTdHJpbmdbXQlzdHJpbmdBcnJheSA9IElEYXRhVXRpbC5n
ZXRTdHJpbmdBcnJheSggcGlwZWxpbmVDdXJzb3IsICJzdHJpbmdBcnJheSIgKTsNCglpbnQgaXRl
bUNvdW50ID0gMDsNCglpbnQgaSA9IDA7DQoJd2hpbGUgKGkgPCBzdHJpbmdBcnJheS5sZW5ndGgp
ew0KCQlpZiAoaW5TdHJpbmcgIT0gbnVsbCkgew0KCQkJDQoJCQlpZiAoc3RyaW5nQXJyYXlbaV0u
ZXF1YWxzKGluU3RyaW5nKSkgew0KDQoJCQkJaXRlbUNvdW50Kys7DQoJCQkJfQ0KCQl9DQoJCWkr
KzsNCgl9DQovLyBwaXBlbGluZQ0KCVN0cmluZyBvdXRTdHJpbmcgPSBTdHJpbmcudmFsdWVPZihp
dGVtQ291bnQpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJvdXRTdHJpbmciLCBv
dXRTdHJpbmcgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCg0KLy8gLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KDQoJ</value>
</Values>
